# Site settings
title: Gian Solo 
email: soundsbygian@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Singer/Songwriter-Producer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://giansolomusic.com" # the base hostname & protocol for your site
twitter_username: gian_solo
instagram_username: gian_solo 


# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed
